---

- name: "Install Packages (apt)"
  action: apt name={{ item }} state=latest update_cache=yes
  with_items:
    - autoconf
    - automake
    - bison
    - bundler
    - flex
    - git
    - libpq-dev
    - postgresql
    - python-dev
    - python-m2crypto
    - python-pip
    - python-psycopg2
    - swig