---

- name: "Add PostgreSQL User"
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name=msf password=msf role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE

- name: "Add PostgreSQL DB"
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_db: name=msf owner=msf

- name: "Create database.yml"
  shell: echo {{ item }} >> ~/database.yml executable=/bin/bash
  with_items:
    - "'production:'"
    - "'  adapter: postgresql'"
    - "'  database: msf'"
    - "'  username: msf'"
    - "'  password: msf'"
    - "'  host: 127.0.0.1'"
    - "'  port: 5432'"
    - "'  pool: 75'"
    - "'  timeout: 5'"

- name: "Move MSF database.yml"
  shell: "mv /root/database.yml /opt/metasploit-framework/embedded/framework/config/database.yml"
  args:
    executable: /bin/bash